// =============================================================================
// Pepertect — Comprehensive NSE/BSE stock universe (under ₹1000)
// =============================================================================
// Source: NSE/BSE listed equities compiled by the product team.
// All entries are deduplicated by symbol. Prices are indicative LTPs
// (₹) as of the latest sweep — the API layer randomizes a small intraday
// change on top of these so the dashboard looks live without needing a
// real-time feed.
// =============================================================================

export interface StockSeed {
  symbol: string;
  name: string;
  ltp: number;
  sector: string;
  lotSize: number;
}

// Helper: most equities default to 1 share lot. F&O stocks use larger lots.
const L1 = 1;

export const STOCKS_UNIVERSE: StockSeed[] = [
  // ---------------- Banking ----------------
  { symbol: 'SBIN',        name: 'State Bank of India',              ltp: 977.70,  sector: 'Banking',         lotSize: 1500 },
  { symbol: 'HDFCBANK',    name: 'HDFC Bank Ltd',                    ltp: 747.05,  sector: 'Banking',         lotSize: 550 },
  { symbol: 'KOTAKBANK',   name: 'Kotak Mahindra Bank Ltd',          ltp: 377.45,  sector: 'Banking',         lotSize: 400 },
  { symbol: 'YESBANK',     name: 'Yes Bank Ltd',                     ltp: 20.35,   sector: 'Banking',         lotSize: L1 },
  { symbol: 'IDFCFIRSTB',  name: 'IDFC First Bank Ltd',              ltp: 80.20,   sector: 'Banking',         lotSize: L1 },
  { symbol: 'UCOBANK',     name: 'UCO Bank',                         ltp: 26.39,   sector: 'Banking',         lotSize: L1 },
  { symbol: 'CENTRALBANK', name: 'Central Bank of India',            ltp: 30.10,   sector: 'Banking',         lotSize: L1 },
  { symbol: 'IOB',         name: 'Indian Overseas Bank',             ltp: 20.45,   sector: 'Banking',         lotSize: L1 },
  { symbol: 'PNB',         name: 'Punjab National Bank',             ltp: 80.30,   sector: 'Banking',         lotSize: L1 },
  { symbol: 'BANKBARODA',  name: 'Bank of Baroda',                   ltp: 150.25,  sector: 'Banking',         lotSize: L1 },
  { symbol: 'CANBK',       name: 'Canara Bank',                      ltp: 400.55,  sector: 'Banking',         lotSize: L1 },
  { symbol: 'BANKINDIA',   name: 'Bank of India',                    ltp: 90.15,   sector: 'Banking',         lotSize: L1 },
  { symbol: 'UNIONBANK',   name: 'Union Bank of India',              ltp: 70.80,   sector: 'Banking',         lotSize: L1 },
  { symbol: 'INDIANB',     name: 'Indian Bank',                      ltp: 350.40,  sector: 'Banking',         lotSize: L1 },
  { symbol: 'IDBI',        name: 'IDBI Bank Ltd',                    ltp: 50.90,   sector: 'Banking',         lotSize: L1 },
  { symbol: 'SOUTHBANK',   name: 'South Indian Bank',                ltp: 25.35,   sector: 'Banking',         lotSize: L1 },
  { symbol: 'KTKBANK',     name: 'Karnataka Bank Ltd',               ltp: 200.10,  sector: 'Banking',         lotSize: L1 },
  { symbol: 'CUB',         name: 'City Union Bank Ltd',              ltp: 150.50,  sector: 'Banking',         lotSize: L1 },
  { symbol: 'DCBBANK',     name: 'DCB Bank Ltd',                     ltp: 100.40,  sector: 'Banking',         lotSize: L1 },
  { symbol: 'RBLBANK',     name: 'RBL Bank Ltd',                     ltp: 200.85,  sector: 'Banking',         lotSize: L1 },
  { symbol: 'INDUSINDBK',  name: 'IndusInd Bank Ltd',                ltp: 800.60,  sector: 'Banking',         lotSize: L1 },
  { symbol: 'BANDHANBNK',  name: 'Bandhan Bank Ltd',                 ltp: 180.40,  sector: 'Banking',         lotSize: L1 },
  { symbol: 'FEDERALBNK',  name: 'Federal Bank Ltd',                 ltp: 150.25,  sector: 'Banking',         lotSize: L1 },

  // ---------------- Insurance & Finance ----------------
  { symbol: 'LICI',        name: 'Life Insurance Corp of India',     ltp: 399.90,  sector: 'Insurance',        lotSize: L1 },
  { symbol: 'HDFCLIFE',    name: 'HDFC Life Insurance',              ltp: 580.40,  sector: 'Insurance',        lotSize: L1 },
  { symbol: 'SBILIFE',     name: 'SBI Life Insurance',               ltp: 1240.50, sector: 'Insurance',        lotSize: L1 },
  { symbol: 'ICICIPRULI',  name: 'ICICI Prudential Life Insurance',  ltp: 510.20,  sector: 'Insurance',        lotSize: L1 },
  { symbol: 'ICICIGI',     name: 'ICICI Lombard General Insurance',  ltp: 1700.40, sector: 'Insurance',        lotSize: L1 },
  { symbol: 'IDFC',        name: 'IDFC Ltd',                         ltp: 80.50,   sector: 'Finance',          lotSize: L1 },
  { symbol: 'BAJAJHLDNG',  name: 'Bajaj Holdings & Investment',      ltp: 8000.10, sector: 'Finance',          lotSize: L1 },
  { symbol: 'SHRIRAMFIN',  name: 'Shriram Transport Finance',        ltp: 1900.50, sector: 'Finance',          lotSize: L1 },
  { symbol: 'MMFIN',       name: 'M&M Financial Services',           ltp: 200.30,  sector: 'Finance',          lotSize: L1 },
  { symbol: 'CHOLAFIN',    name: 'Cholamandalam Investment',         ltp: 1200.45, sector: 'Finance',          lotSize: L1 },
  { symbol: 'LTF',         name: 'L&T Finance Holdings',             ltp: 145.20,  sector: 'Finance',          lotSize: L1 },
  { symbol: 'BAJFINANCE',  name: 'Bajaj Finance Ltd',                ltp: 889.40,  sector: 'Finance',          lotSize: 125 },
  { symbol: 'BAJAJFINSV',  name: 'Bajaj Finserv Ltd',                ltp: 1500.30, sector: 'Finance',          lotSize: L1 },
  { symbol: 'PFC',         name: 'Power Finance Corp',               ltp: 380.40,  sector: 'Finance',          lotSize: L1 },
  { symbol: 'RECLTD',      name: 'REC Ltd',                          ltp: 410.20,  sector: 'Finance',          lotSize: L1 },
  { symbol: 'MUTHOOTFIN',  name: 'Muthoot Finance Ltd',              ltp: 1700.50, sector: 'Finance',          lotSize: L1 },

  // ---------------- Energy & Power ----------------
  { symbol: 'NTPC',        name: 'NTPC Ltd',                         ltp: 361.65,  sector: 'Energy',           lotSize: L1 },
  { symbol: 'ADANIPOWER',  name: 'Adani Power Ltd',                  ltp: 232.60,  sector: 'Energy',           lotSize: L1 },
  { symbol: 'JSWENERGY',   name: 'JSW Energy Ltd',                   ltp: 831.90,  sector: 'Energy',           lotSize: L1 },
  { symbol: 'POWERGRID',   name: 'Power Grid Corporation',           ltp: 222.10,  sector: 'Energy',           lotSize: L1 },
  { symbol: 'ADANIGREEN',  name: 'Adani Green Energy',               ltp: 800.40,  sector: 'Energy',           lotSize: L1 },
  { symbol: 'ADANITRANS',  name: 'Adani Transmission',               ltp: 800.30,  sector: 'Energy',           lotSize: L1 },
  { symbol: 'TATAPOWER',   name: 'Tata Power Co. Ltd',               ltp: 320.50,  sector: 'Energy',           lotSize: L1 },
  { symbol: 'NHPC',        name: 'NHPC Ltd',                         ltp: 80.40,   sector: 'Energy',           lotSize: L1 },
  { symbol: 'SUZLON',      name: 'Suzlon Energy Ltd',                ltp: 25.40,   sector: 'Energy',           lotSize: L1 },
  { symbol: 'ONGC',        name: 'Oil & Natural Gas Corp',           ltp: 215.50,  sector: 'Oil & Gas',        lotSize: L1 },
  { symbol: 'IOC',         name: 'Indian Oil Corporation',           ltp: 138.57,  sector: 'Oil & Gas',        lotSize: L1 },
  { symbol: 'BPCL',        name: 'Bharat Petroleum Corp',            ltp: 305.40,  sector: 'Oil & Gas',        lotSize: L1 },
  { symbol: 'HINDPETRO',   name: 'Hindustan Petroleum',              ltp: 380.20,  sector: 'Oil & Gas',        lotSize: L1 },
  { symbol: 'RELIANCE',    name: 'Reliance Industries',              ltp: 1280.50, sector: 'Oil & Gas',        lotSize: 250 },
  { symbol: 'OIL',         name: 'Oil India Ltd',                    ltp: 410.50,  sector: 'Oil & Gas',        lotSize: L1 },
  { symbol: 'GAIL',        name: 'GAIL India Ltd',                   ltp: 180.30,  sector: 'Oil & Gas',        lotSize: L1 },
  { symbol: 'PETRONET',    name: 'Petronet LNG Ltd',                 ltp: 290.40,  sector: 'Oil & Gas',        lotSize: L1 },
  { symbol: 'GUJGASLTD',   name: 'Gujarat Gas Ltd',                  ltp: 540.20,  sector: 'Oil & Gas',        lotSize: L1 },
  { symbol: 'IGL',         name: 'Indraprastha Gas Ltd',             ltp: 460.50,  sector: 'Oil & Gas',        lotSize: L1 },
  { symbol: 'MGL',         name: 'Mahanagar Gas Ltd',                ltp: 800.40,  sector: 'Oil & Gas',        lotSize: L1 },
  { symbol: 'COALINDIA',   name: 'Coal India Ltd',                   ltp: 423.10,  sector: 'Mining',           lotSize: L1 },

  // ---------------- FMCG ----------------
  { symbol: 'ITC',         name: 'ITC Ltd',                          ltp: 280.70,  sector: 'FMCG',             lotSize: 1600 },
  { symbol: 'HINDUNILVR',  name: 'Hindustan Unilever Ltd',           ltp: 2534.10, sector: 'FMCG',             lotSize: 300 },
  { symbol: 'NESTLEIND',   name: 'Nestle India Ltd',                 ltp: 2200.40, sector: 'FMCG',             lotSize: L1 },
  { symbol: 'BRITANNIA',   name: 'Britannia Industries',             ltp: 4800.50, sector: 'FMCG',             lotSize: L1 },
  { symbol: 'DABUR',       name: 'Dabur India Ltd',                  ltp: 510.40,  sector: 'FMCG',             lotSize: L1 },
  { symbol: 'MARICO',      name: 'Marico Ltd',                       ltp: 540.20,  sector: 'FMCG',             lotSize: L1 },
  { symbol: 'GODREJCP',    name: 'Godrej Consumer Products',         ltp: 1100.40, sector: 'FMCG',             lotSize: L1 },
  { symbol: 'COLPAL',      name: 'Colgate-Palmolive India',          ltp: 2400.50, sector: 'FMCG',             lotSize: L1 },
  { symbol: 'PGHH',        name: 'Procter & Gamble Hygiene',         ltp: 15000.20, sector: 'FMCG',            lotSize: L1 },
  { symbol: 'EMAMILTD',    name: 'Emami Ltd',                        ltp: 500.30,  sector: 'FMCG',             lotSize: L1 },
  { symbol: 'TATACONSUM',  name: 'Tata Consumer Products',           ltp: 800.40,  sector: 'FMCG',             lotSize: L1 },
  { symbol: 'VBL',         name: 'Varun Beverages Ltd',              ltp: 800.50,  sector: 'FMCG',             lotSize: L1 },
  { symbol: 'JUBLFOOD',    name: 'Jubilant FoodWorks Ltd',           ltp: 400.20,  sector: 'FMCG',             lotSize: L1 },
  { symbol: 'WESTLIFE',    name: 'Westlife Development',             ltp: 800.40,  sector: 'FMCG',             lotSize: L1 },
  { symbol: 'RBA',         name: 'Restaurant Brands Asia',           ltp: 100.30,  sector: 'FMCG',             lotSize: L1 },
  { symbol: 'DEVYANI',     name: 'Devyani International',            ltp: 150.20,  sector: 'FMCG',             lotSize: L1 },
  { symbol: 'SAPPHIRE',    name: 'Sapphire Foods India',             ltp: 300.40,  sector: 'FMCG',             lotSize: L1 },
  { symbol: 'BARBEQUE',    name: 'Barbeque-Nation Hospitality',      ltp: 1100.20, sector: 'FMCG',             lotSize: L1 },
  { symbol: 'AWL',         name: 'Adani Wilmar Ltd',                 ltp: 300.40,  sector: 'FMCG',             lotSize: L1 },
  { symbol: 'UBL',         name: 'United Breweries Ltd',             ltp: 1800.20, sector: 'FMCG',             lotSize: L1 },
  { symbol: 'MCDOWELL',    name: 'McDowell Holdings',                ltp: 100.20,  sector: 'FMCG',             lotSize: L1 },

  // ---------------- Metals & Mining ----------------
  { symbol: 'HINDALCO',    name: 'Hindalco Industries',              ltp: 933.05,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'JSL',         name: 'Jindal Stainless Ltd',             ltp: 945.00,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'JSWSTEEL',    name: 'JSW Steel Ltd',                    ltp: 940.50,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'TATASTEEL',   name: 'Tata Steel Ltd',                   ltp: 155.20,  sector: 'Metals',           lotSize: 550 },
  { symbol: 'SAIL',        name: 'Steel Authority of India',         ltp: 130.40,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'NMDC',        name: 'NMDC Ltd',                         ltp: 230.50,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'MOIL',        name: 'MOIL Ltd',                         ltp: 380.20,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'VEDL',        name: 'Vedanta Ltd',                      ltp: 410.50,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'HINDZINC',    name: 'Hindustan Zinc Ltd',               ltp: 500.40,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'JINDALSTEL',  name: 'Jindal Steel & Power',             ltp: 940.50,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'JINDALSAW',   name: 'Jindal Saw Ltd',                  ltp: 380.20,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'WELCORP',     name: 'Welspun Corp Ltd',                 ltp: 580.50,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'RATNAMANI',   name: 'Ratnamani Metals & Tubes',         ltp: 1500.20, sector: 'Metals',           lotSize: L1 },
  { symbol: 'APLAPOLLO',   name: 'APL Apollo Tubes Ltd',             ltp: 1400.40, sector: 'Metals',           lotSize: L1 },
  { symbol: 'GODAWARI',    name: 'Godawari Power & Ispat',           ltp: 540.50,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'MAHSEAMLES',  name: 'Maharashtra Seamless',             ltp: 800.20,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'MANINDS',     name: 'Man Industries India',             ltp: 200.30,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'GOODLUCK',    name: 'Goodluck India Ltd',               ltp: 800.40,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'PRAKASH',     name: 'Prakash Industries',               ltp: 200.20,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'LLOYDSME',    name: 'Lloyds Metals & Energy',           ltp: 800.50,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'SUNFLAG',     name: 'Sunflag Iron & Steel',             ltp: 200.40,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'USHAMART',    name: 'Usha Martin Ltd',                  ltp: 380.20,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'KALYANI',     name: 'Kalyani Steels Ltd',               ltp: 540.40,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'MUKANDLTD',   name: 'Mukand Ltd',                       ltp: 100.50,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'NATIONALUM',  name: 'National Aluminium Co.',           ltp: 180.40,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'HINDCOPPER',  name: 'Hindustan Copper Ltd',             ltp: 350.20,  sector: 'Metals',           lotSize: L1 },
  { symbol: 'GRAVITA',     name: 'Gravita India Ltd',                ltp: 540.50,  sector: 'Metals',           lotSize: L1 },

  // ---------------- Automobile ----------------
  { symbol: 'TATAMOTORS',  name: 'Tata Motors Ltd',                  ltp: 320.50,  sector: 'Automobile',       lotSize: 550 },
  { symbol: 'M&M',         name: 'Mahindra & Mahindra',              ltp: 940.50,  sector: 'Automobile',       lotSize: 700 },
  { symbol: 'MARUTI',      name: 'Maruti Suzuki India',              ltp: 12450.80, sector: 'Automobile',      lotSize: 50 },
  { symbol: 'BAJAJ-AUTO',  name: 'Bajaj Auto Ltd',                   ltp: 8000.40, sector: 'Automobile',       lotSize: L1 },
  { symbol: 'HEROMOTOCO',  name: 'Hero MotoCorp Ltd',                ltp: 4500.20, sector: 'Automobile',       lotSize: L1 },
  { symbol: 'EICHERMOT',   name: 'Eicher Motors Ltd',                ltp: 4900.50, sector: 'Automobile',       lotSize: L1 },
  { symbol: 'TVSMOTOR',    name: 'TVS Motor Company',                ltp: 2400.20, sector: 'Automobile',       lotSize: L1 },
  { symbol: 'ASHOKLEY',    name: 'Ashok Leyland Ltd',                ltp: 220.40,  sector: 'Automobile',       lotSize: L1 },
  { symbol: 'FORCEMOT',    name: 'Force Motors Ltd',                 ltp: 8000.50, sector: 'Automobile',       lotSize: L1 },
  { symbol: 'SMLISUZU',    name: 'SML Isuzu Ltd',                    ltp: 1000.20, sector: 'Automobile',       lotSize: L1 },
  { symbol: 'TATAMTRDVR',  name: 'Tata Motors DVR',                  ltp: 200.40,  sector: 'Automobile',       lotSize: L1 },

  // ---------------- Auto Parts ----------------
  { symbol: 'MOTHERSON',   name: 'Motherson Sumi Systems',           ltp: 130.50,  sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'EXIDEIND',    name: 'Exide Industries',                 ltp: 480.20,  sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'AMARAJABAT',  name: 'Amara Raja Batteries',             ltp: 970.50,  sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'BOSCHLTD',    name: 'Bosch Ltd',                        ltp: 35000.20, sector: 'Auto Parts',      lotSize: L1 },
  { symbol: 'MRF',         name: 'MRF Ltd',                          ltp: 135000.40, sector: 'Auto Parts',     lotSize: L1 },
  { symbol: 'APOLLOTYRE',  name: 'Apollo Tyres Ltd',                 ltp: 460.20,  sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'CEATLTD',     name: 'CEAT Ltd',                         ltp: 2400.50, sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'JKTYRE',      name: 'JK Tyre & Industries',             ltp: 380.20,  sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'SUNDRMFAST',  name: 'Sundram Fasteners',                ltp: 540.50,  sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'BHARATFORG',  name: 'Bharat Forge Ltd',                 ltp: 1100.20, sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'MINDAIND',    name: 'Minda Industries',                 ltp: 540.20,  sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'LUMAXIND',    name: 'Lumax Industries',                 ltp: 1500.50, sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'GABRIEL',     name: 'Gabriel India Ltd',                ltp: 280.40,  sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'JAMNAAUTO',   name: 'Jamna Auto Industries',            ltp: 200.50,  sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'RANEHOLDIN',  name: 'Rane Holdings Ltd',                ltp: 800.20,  sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'RANEENGINE',  name: 'Rane Engine Valves',               ltp: 200.40,  sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'RANEBRAKE',   name: 'Rane Brake Lining',                ltp: 540.50,  sector: 'Auto Parts',       lotSize: L1 },
  { symbol: 'SETCO',       name: 'Setco Automotive',                 ltp: 50.20,   sector: 'Auto Parts',       lotSize: L1 },

  // ---------------- Paints ----------------
  { symbol: 'ASIANPAINT',  name: 'Asian Paints Ltd',                 ltp: 3100.20, sector: 'Paints',           lotSize: L1 },
  { symbol: 'BERGERPAINT', name: 'Berger Paints India',              ltp: 510.40,  sector: 'Paints',           lotSize: L1 },
  { symbol: 'AKZOINDIA',   name: 'Akzo Nobel India',                 ltp: 2800.50, sector: 'Paints',           lotSize: L1 },
  { symbol: 'KANSAINER',   name: 'Kansai Nerolac Paints',            ltp: 350.20,  sector: 'Paints',           lotSize: L1 },
  { symbol: 'INDIGOPNT',   name: 'Indigo Paints Ltd',                ltp: 1100.40, sector: 'Paints',           lotSize: L1 },
  { symbol: 'SHALPAINTS',  name: 'Shalimar Paints',                  ltp: 200.30,  sector: 'Paints',           lotSize: L1 },

  // ---------------- Telecom ----------------
  { symbol: 'BHARTIARTL',  name: 'Bharti Airtel Ltd',                ltp: 1400.50, sector: 'Telecom',          lotSize: 475 },
  { symbol: 'IDEA',        name: 'Vodafone Idea Ltd',                ltp: 14.20,   sector: 'Telecom',          lotSize: L1 },
  { symbol: 'INDUSTOWER',  name: 'Indus Towers Ltd',                 ltp: 410.50,  sector: 'Telecom',          lotSize: L1 },
  { symbol: 'TATACOMM',    name: 'Tata Communications',              ltp: 1800.20, sector: 'Telecom',          lotSize: L1 },
  { symbol: 'TEJASNET',    name: 'Tejas Networks',                   ltp: 800.40,  sector: 'Telecom',          lotSize: L1 },

  // ---------------- IT ----------------
  { symbol: 'TCS',         name: 'Tata Consultancy Services',        ltp: 3945.60, sector: 'IT',               lotSize: 150 },
  { symbol: 'INFY',        name: 'Infosys Ltd',                      ltp: 1568.30, sector: 'IT',               lotSize: 300 },
  { symbol: 'WIPRO',       name: 'Wipro Ltd',                        ltp: 572.60,  sector: 'IT',               lotSize: 1500 },
  { symbol: 'HCLTECH',     name: 'HCL Technologies',                 ltp: 1712.40, sector: 'IT',               lotSize: 350 },
  { symbol: 'TECHM',       name: 'Tech Mahindra',                    ltp: 1500.20, sector: 'IT',               lotSize: L1 },
  { symbol: 'LTIM',        name: 'LTIMindtree',                      ltp: 5400.50, sector: 'IT',               lotSize: L1 },
  { symbol: 'PERSISTENT',  name: 'Persistent Systems',               ltp: 4800.20, sector: 'IT',               lotSize: L1 },
  { symbol: 'COFORGE',     name: 'Coforge Ltd',                      ltp: 5400.40, sector: 'IT',               lotSize: L1 },
  { symbol: 'MPHASIS',     name: 'Mphasis Ltd',                      ltp: 2400.50, sector: 'IT',               lotSize: L1 },
  { symbol: 'OFSS',        name: 'Oracle Financial Services',        ltp: 9800.20, sector: 'IT',               lotSize: L1 },

  // ---------------- Pharma & Healthcare ----------------
  { symbol: 'SUNPHARMA',   name: 'Sun Pharmaceutical',               ltp: 1824.15, sector: 'Pharma',           lotSize: 700 },
  { symbol: 'DRREDDY',     name: "Dr Reddy's Laboratories",          ltp: 5900.20, sector: 'Pharma',           lotSize: L1 },
  { symbol: 'CIPLA',       name: 'Cipla Ltd',                        ltp: 1500.40, sector: 'Pharma',           lotSize: L1 },
  { symbol: 'DIVISLAB',    name: 'Divis Laboratories',               ltp: 5800.50, sector: 'Pharma',           lotSize: L1 },
  { symbol: 'LUPIN',       name: 'Lupin Ltd',                        ltp: 1500.20, sector: 'Pharma',           lotSize: L1 },
  { symbol: 'AUROPHARMA',  name: 'Aurobindo Pharma',                 ltp: 1100.40, sector: 'Pharma',           lotSize: L1 },
  { symbol: 'BIOCON',      name: 'Biocon Ltd',                       ltp: 320.50,  sector: 'Pharma',           lotSize: L1 },
  { symbol: 'SYNGENE',     name: 'Syngene International',            ltp: 800.20,  sector: 'Pharma',           lotSize: L1 },
  { symbol: 'CADILAHC',    name: 'Zydus Lifesciences',               ltp: 540.40,  sector: 'Pharma',           lotSize: L1 },
  { symbol: 'TORNTPHARM',  name: 'Torrent Pharmaceuticals',          ltp: 3000.50, sector: 'Pharma',           lotSize: L1 },
  { symbol: 'APLLTD',      name: 'Alembic Pharmaceuticals',          ltp: 540.20,  sector: 'Pharma',           lotSize: L1 },
  { symbol: 'ABBOTINDIA',  name: 'Abbott India Ltd',                 ltp: 30000.40, sector: 'Pharma',          lotSize: L1 },
  { symbol: 'GLENMARK',    name: 'Glenmark Pharma',                  ltp: 1000.20, sector: 'Pharma',           lotSize: L1 },
  { symbol: 'IPCALAB',     name: 'Ipca Laboratories',                ltp: 1300.40, sector: 'Pharma',           lotSize: L1 },
  { symbol: 'JBIL',        name: 'J.B. Chemicals & Pharma',          ltp: 1800.50, sector: 'Pharma',           lotSize: L1 },

  // ---------------- Infrastructure & Construction ----------------
  { symbol: 'LT',          name: 'Larsen & Toubro Ltd',              ltp: 3542.65, sector: 'Infrastructure',   lotSize: 150 },
  { symbol: 'ULTRACEMCO',  name: 'UltraTech Cement',                 ltp: 11000.20, sector: 'Cement',          lotSize: L1 },
  { symbol: 'SHREECEM',    name: 'Shree Cement Ltd',                 ltp: 28000.40, sector: 'Cement',          lotSize: L1 },
  { symbol: 'GRASIM',      name: 'Grasim Industries',                ltp: 2400.50, sector: 'Cement',           lotSize: L1 },
  { symbol: 'AMBUJACEM',   name: 'Ambuja Cements',                   ltp: 580.20,  sector: 'Cement',           lotSize: L1 },
  { symbol: 'ACC',         name: 'ACC Ltd',                          ltp: 2200.40, sector: 'Cement',           lotSize: L1 },
  { symbol: 'RAMCOCEM',    name: 'Ramco Cements',                    ltp: 800.50,  sector: 'Cement',           lotSize: L1 },
  { symbol: 'DALMIASUG',   name: 'Dalmia Bharat Sugar',              ltp: 410.20,  sector: 'Cement',           lotSize: L1 },
  { symbol: 'GMRINFRA',    name: 'GMR Infrastructure',               ltp: 80.40,   sector: 'Infrastructure',    lotSize: L1 },
  { symbol: 'IRB',         name: 'IRB Infrastructure Developers',    ltp: 80.50,   sector: 'Infrastructure',    lotSize: L1 },
  { symbol: 'NBCC',        name: 'NBCC India Ltd',                   ltp: 110.20,  sector: 'Infrastructure',    lotSize: L1 },
  { symbol: 'NCC',         name: 'NCC Ltd',                          ltp: 200.40,  sector: 'Infrastructure',    lotSize: L1 },
  { symbol: 'SJVN',        name: 'SJVN Ltd',                         ltp: 100.20,  sector: 'Infrastructure',    lotSize: L1 },
  { symbol: 'RVNL',        name: 'Rail Vikas Nigam',                 ltp: 410.50,  sector: 'Infrastructure',    lotSize: L1 },
  { symbol: 'IRFC',        name: 'Indian Railway Finance',           ltp: 140.20,  sector: 'Infrastructure',    lotSize: L1 },
  { symbol: 'MAZDOCK',     name: 'Mazagon Dock Shipbuilders',        ltp: 4400.50, sector: 'Infrastructure',    lotSize: L1 },
  { symbol: 'CochinSHIP',  name: 'Cochin Shipyard',                  ltp: 1500.20, sector: 'Infrastructure',    lotSize: L1 },
  { symbol: 'HAL',         name: 'Hindustan Aeronautics',            ltp: 4800.40, sector: 'Aerospace',         lotSize: L1 },
  { symbol: 'BEL',         name: 'Bharat Electronics',               ltp: 280.20,  sector: 'Aerospace',         lotSize: L1 },
  { symbol: 'BEML',        name: 'BEML Ltd',                         ltp: 3500.50, sector: 'Aerospace',         lotSize: L1 },

  // ---------------- Textiles ----------------
  { symbol: 'ALOKINDS',    name: 'Alok Industries',                  ltp: 25.40,   sector: 'Textiles',          lotSize: L1 },
  { symbol: 'CENTURYTEX',  name: 'Century Textiles & Industries',    ltp: 1500.20, sector: 'Textiles',          lotSize: L1 },
  { symbol: 'TRIDENT',     name: 'Trident Ltd',                      ltp: 40.50,   sector: 'Textiles',          lotSize: L1 },
  { symbol: 'VARDHMAN',    name: 'Vardhman Textiles',                ltp: 410.20,  sector: 'Textiles',          lotSize: L1 },
  { symbol: 'ARVIND',      name: 'Arvind Ltd',                       ltp: 280.40,  sector: 'Textiles',          lotSize: L1 },
  { symbol: 'RAYMOND',     name: 'Raymond Ltd',                      ltp: 1900.50, sector: 'Textiles',          lotSize: L1 },
  { symbol: 'BOMDYEING',   name: 'Bombay Dyeing',                    ltp: 200.20,  sector: 'Textiles',          lotSize: L1 },
  { symbol: 'WELSPUNIND',  name: 'Welspun India',                    ltp: 540.40,  sector: 'Textiles',          lotSize: L1 },
  { symbol: 'PAGEIND',     name: 'Page Industries',                  ltp: 38000.20, sector: 'Textiles',         lotSize: L1 },
  { symbol: 'GOKALDAS',    name: 'Gokaldas Exports',                 ltp: 970.50,  sector: 'Textiles',          lotSize: L1 },
  { symbol: 'KPRMILL',     name: 'KPR Mill Ltd',                     ltp: 800.20,  sector: 'Textiles',          lotSize: L1 },
  { symbol: 'JBFIND',      name: 'JBF Industries',                   ltp: 5.40,    sector: 'Textiles',          lotSize: L1 },
  { symbol: 'NAHARSPING',  name: 'Nahar Spinning Mills',             ltp: 410.20,  sector: 'Textiles',          lotSize: L1 },
  { symbol: 'SUTLEJTEX',   name: 'Sutlej Textiles',                  ltp: 100.40,  sector: 'Textiles',          lotSize: L1 },
  { symbol: 'RUPA',        name: 'Rupa & Company',                   ltp: 280.50,  sector: 'Textiles',          lotSize: L1 },
  { symbol: 'DOLLAR',      name: 'Dollar Industries',                ltp: 540.20,  sector: 'Textiles',          lotSize: L1 },
  { symbol: 'LUXIND',      name: 'Lux Industries',                   ltp: 1500.40, sector: 'Textiles',          lotSize: L1 },
  { symbol: 'MONTECARLO',  name: 'Monte Carlo Fashions',             ltp: 540.50,  sector: 'Textiles',          lotSize: L1 },

  // ---------------- Retail ----------------
  { symbol: 'DMART',       name: 'Avenue Supermarts',                ltp: 4400.20, sector: 'Retail',           lotSize: L1 },
  { symbol: 'TRENT',       name: 'Trent Ltd',                        ltp: 6800.40, sector: 'Retail',           lotSize: L1 },
  { symbol: 'ABFRL',       name: 'Aditya Birla Fashion',             ltp: 280.50,  sector: 'Retail',           lotSize: L1 },
  { symbol: 'SHOPERSTOP',  name: "Shoppers Stop",                    ltp: 540.20,  sector: 'Retail',           lotSize: L1 },
  { symbol: 'VMART',       name: 'V-Mart Retail',                    ltp: 2900.40, sector: 'Retail',           lotSize: L1 },
  { symbol: 'FRETAIL',     name: 'Future Retail',                    ltp: 5.20,    sector: 'Retail',           lotSize: L1 },
  { symbol: 'CANTABIL',    name: 'Cantabil Retail India',            ltp: 540.20,  sector: 'Retail',           lotSize: L1 },
  { symbol: 'ZOMATO',      name: 'Zomato Ltd',                       ltp: 240.50,  sector: 'Retail',           lotSize: L1 },
  { symbol: 'NYKAA',       name: 'FSN E-Commerce (Nykaa)',           ltp: 180.40,  sector: 'Retail',           lotSize: L1 },
  { symbol: 'PAYTM',       name: 'One 97 Communications (Paytm)',    ltp: 410.20,  sector: 'Retail',           lotSize: L1 },
  { symbol: 'PBFINTECH',   name: 'PB Fintech (PolicyBazaar)',        ltp: 1300.50, sector: 'Retail',           lotSize: L1 },
  { symbol: 'IEX',         name: 'Indian Energy Exchange',           ltp: 130.40,  sector: 'Retail',           lotSize: L1 },

  // ---------------- Consumer Goods & Electricals ----------------
  { symbol: 'TITAN',       name: 'Titan Company',                    ltp: 3400.20, sector: 'Consumer',         lotSize: 175 },
  { symbol: 'PIDILITIND',  name: 'Pidilite Industries',              ltp: 2900.50, sector: 'Consumer',         lotSize: L1 },
  { symbol: 'HAVELLS',     name: 'Havells India',                    ltp: 1500.20, sector: 'Consumer',         lotSize: L1 },
  { symbol: 'BATAINDIA',   name: 'Bata India',                       ltp: 1300.40, sector: 'Consumer',         lotSize: L1 },
  { symbol: 'VOLTAS',      name: 'Voltas Ltd',                       ltp: 1300.50, sector: 'Consumer',         lotSize: L1 },
  { symbol: 'DIXON',       name: 'Dixon Technologies',               ltp: 13000.20, sector: 'Consumer',        lotSize: L1 },
  { symbol: 'POLYCAB',     name: 'Polycab India',                    ltp: 6500.40, sector: 'Consumer',         lotSize: L1 },
  { symbol: 'BAJAJELEC',   name: 'Bajaj Electricals',                ltp: 1100.20, sector: 'Consumer',         lotSize: L1 },
  { symbol: 'VGuard',      name: 'V-Guard Industries',               ltp: 320.40,  sector: 'Consumer',         lotSize: L1 },
  { symbol: 'ORIENTELEC',  name: 'Orient Electric',                  ltp: 240.20,  sector: 'Consumer',         lotSize: L1 },
  { symbol: 'TTKPRESTIGE', name: 'TTK Prestige',                     ltp: 800.50,  sector: 'Consumer',         lotSize: L1 },
  { symbol: 'STOVEKRAFT',  name: 'Stove Kraft',                     ltp: 540.20,  sector: 'Consumer',         lotSize: L1 },

  // ---------------- Agri, Sugar & Tea ----------------
  { symbol: 'BALRAMCHIN',  name: 'Balrampur Chini Mills',            ltp: 460.20,  sector: 'Sugar',            lotSize: L1 },
  { symbol: 'EIDPARRY',    name: 'EID Parry India',                  ltp: 540.40,  sector: 'Sugar',            lotSize: L1 },
  { symbol: 'DHAMPURSUG',  name: 'Dhampur Sugar Mills',              ltp: 240.50,  sector: 'Sugar',            lotSize: L1 },
  { symbol: 'BAJAJHIND',   name: 'Bajaj Hindusthan Sugar',           ltp: 280.20,  sector: 'Sugar',            lotSize: L1 },
  { symbol: 'MAGADSUGAR',  name: 'Magadh Sugar & Energy',            ltp: 540.40,  sector: 'Sugar',            lotSize: L1 },
  { symbol: 'DWARKESH',    name: 'Dwarkesh Sugar',                   ltp: 200.50,  sector: 'Sugar',            lotSize: L1 },
  { symbol: 'TRIDENTTEA',  name: 'McLeod Russel India',              ltp: 30.20,   sector: 'Tea',              lotSize: L1 },
  { symbol: 'HARRMALAYA',  name: 'Harrisons Malayalam',              ltp: 200.40,  sector: 'Tea',              lotSize: L1 },
  { symbol: 'TATA COFFEE', name: 'Tata Coffee Ltd',                  ltp: 240.50,  sector: 'Tea',              lotSize: L1 },
  { symbol: 'ROSSARI',     name: 'Rossari Biotech',                  ltp: 800.20,  sector: 'Chemicals',         lotSize: L1 },
  { symbol: 'PIIND',       name: 'PI Industries',                    ltp: 3700.40, sector: 'Agri',             lotSize: L1 },
  { symbol: 'UPL',         name: 'UPL Ltd',                          ltp: 540.50,  sector: 'Agri',             lotSize: L1 },
  { symbol: 'COROMANDEL',  name: 'Coromandel International',         ltp: 1200.20, sector: 'Agri',             lotSize: L1 },
  { symbol: 'RALLIS',      name: 'Rallis India',                     ltp: 280.40,  sector: 'Agri',             lotSize: L1 },
  { symbol: 'CHAMBLFERT',  name: 'Chambal Fertilisers',              ltp: 410.20,  sector: 'Agri',             lotSize: L1 },
  { symbol: 'GNFC',        name: 'Gujarat Narmada Valley Fertilizers', ltp: 580.50, sector: 'Agri',           lotSize: L1 },
  { symbol: 'GSFC',        name: 'Gujarat State Fertilizers',        ltp: 220.40,  sector: 'Agri',             lotSize: L1 },
  { symbol: 'FACT',        name: 'Fertilisers & Chemicals Travancore', ltp: 540.20, sector: 'Agri',           lotSize: L1 },
  { symbol: 'RCF',         name: 'Rashtriya Chemicals & Fertilizers', ltp: 130.50, sector: 'Agri',            lotSize: L1 },

  // ---------------- Chemicals & Plastics ----------------
  { symbol: 'SRF',         name: 'SRF Ltd',                          ltp: 4200.20, sector: 'Chemicals',         lotSize: L1 },
  { symbol: 'PIRAMALIND',  name: 'Piramal Enterprises',              ltp: 970.50,  sector: 'Chemicals',         lotSize: L1 },
  { symbol: 'TATACHEM',    name: 'Tata Chemicals',                   ltp: 1000.20, sector: 'Chemicals',         lotSize: L1 },
  { symbol: 'FINEORG',     name: 'Fine Organic Industries',          ltp: 4600.40, sector: 'Chemicals',         lotSize: L1 },
  { symbol: 'AARTIIND',    name: 'Aarti Industries',                 ltp: 540.50,  sector: 'Chemicals',         lotSize: L1 },
  { symbol: 'ATUL',        name: 'Atul Ltd',                         ltp: 5800.20, sector: 'Chemicals',         lotSize: L1 },
  { symbol: 'DEEPAKNTR',   name: 'Deepak Nitrite',                   ltp: 2400.40, sector: 'Chemicals',         lotSize: L1 },
  { symbol: 'NAVINFLUOR',  name: 'Navin Fluorine International',     ltp: 3000.20, sector: 'Chemicals',         lotSize: L1 },
  { symbol: 'LINDEINDIA',  name: 'Linde India',                      ltp: 6000.40, sector: 'Chemicals',         lotSize: L1 },
  { symbol: 'RELAXO',      name: 'Relaxo Footwears',                 ltp: 800.50,  sector: 'Consumer',          lotSize: L1 },
  { symbol: 'SUPREMEIND',  name: 'Supreme Industries',               ltp: 4400.20, sector: 'Plastics',          lotSize: L1 },
  { symbol: 'FINPIPE',     name: 'Finolex Industries',               ltp: 1100.40, sector: 'Plastics',          lotSize: L1 },
  { symbol: 'ASTRAL',      name: 'Astral Ltd',                       ltp: 1800.50, sector: 'Plastics',          lotSize: L1 },
  { symbol: 'PRINCEPIPE',  name: 'Prince Pipes & Fittings',          ltp: 410.20,  sector: 'Plastics',          lotSize: L1 },

  // ---------------- Packaging & Paper ----------------
  { symbol: 'TCPLPACK',    name: 'TCPL Packaging',                   ltp: 1500.40, sector: 'Packaging',         lotSize: L1 },
  { symbol: 'EPL',         name: 'EPL Ltd',                          ltp: 180.50,  sector: 'Packaging',         lotSize: L1 },
  { symbol: 'POLYPLEX',    name: 'Polyplex Corporation',             ltp: 800.20,  sector: 'Packaging',         lotSize: L1 },
  { symbol: 'BSOFT',       name: 'Balmer Lawrie & Co.',              ltp: 320.40,  sector: 'Packaging',         lotSize: L1 },
  { symbol: 'JKPAPER',     name: 'JK Paper Ltd',                     ltp: 410.20,  sector: 'Paper',             lotSize: L1 },
  { symbol: 'WSTCSTPAPER', name: 'West Coast Paper Mills',           ltp: 540.40,  sector: 'Paper',             lotSize: L1 },
  { symbol: 'ORIENTPAP',   name: 'Orient Paper & Industries',        ltp: 50.20,   sector: 'Paper',             lotSize: L1 },
  { symbol: 'SIKKIM',      name: 'Sikkim Pulp & Paper',              ltp: 5.40,    sector: 'Paper',             lotSize: L1 },

  // ---------------- Media & Entertainment ----------------
  { symbol: 'PVR',         name: 'PVR Ltd',                          ltp: 1300.40, sector: 'Media',            lotSize: L1 },
  { symbol: 'INOXLEISUR',  name: 'Inox Leisure',                     ltp: 540.50,  sector: 'Media',            lotSize: L1 },
  { symbol: 'SUNTV',       name: 'Sun TV Network',                   ltp: 540.20,  sector: 'Media',            lotSize: L1 },
  { symbol: 'ZEEENT',      name: 'Zee Entertainment',                ltp: 130.40,  sector: 'Media',            lotSize: L1 },
  { symbol: 'TV18BRDCST',  name: 'TV18 Broadcast',                   ltp: 8.50,    sector: 'Media',            lotSize: L1 },
  { symbol: 'NDTV',        name: 'New Delhi Television',             ltp: 220.20,  sector: 'Media',            lotSize: L1 },
  { symbol: 'NETWORK18',   name: 'Network18 Media & Investments',    ltp: 80.40,   sector: 'Media',            lotSize: L1 },
  { symbol: 'TIPSFILMS',   name: 'Tips Music',                       ltp: 540.50,  sector: 'Media',            lotSize: L1 },
  { symbol: 'SAREGAMA',    name: 'Saregama India',                   ltp: 410.20,  sector: 'Media',            lotSize: L1 },
  { symbol: 'PENIND',      name: 'Pentamedia Graphics',              ltp: 5.40,    sector: 'Media',            lotSize: L1 },
  { symbol: 'HINDMEDIA',   name: 'Hindustan Media Ventures',         ltp: 50.20,   sector: 'Media',            lotSize: L1 },

  // ---------------- Hospitality & Travel ----------------
  { symbol: 'INDHOTEL',    name: 'Indian Hotels Company',            ltp: 680.40,  sector: 'Hospitality',       lotSize: L1 },
  { symbol: 'EIHOTEL',     name: 'EIH Ltd (Oberoi)',                 ltp: 320.20,  sector: 'Hospitality',       lotSize: L1 },
  { symbol: 'CHALET',      name: 'Chalet Hotels',                    ltp: 800.50,  sector: 'Hospitality',       lotSize: L1 },
  { symbol: 'Mahindra Holidays', name: 'Mahindra Holidays & Resorts India', ltp: 440.40, sector: 'Hospitality', lotSize: L1 },
  { symbol: 'TAJGVK',      name: 'TAJ GVK Hotels & Resorts',         ltp: 350.20,  sector: 'Hospitality',       lotSize: L1 },
  { symbol: 'ROYALORCH',   name: 'Royal Orchid Hotels',              ltp: 280.40,  sector: 'Hospitality',       lotSize: L1 },
  { symbol: 'BJFN',        name: 'Bajaj Consumer Care',              ltp: 220.50,  sector: 'Hospitality',       lotSize: L1 },
  { symbol: 'EASMYTRIP',   name: 'Easy Trip Planners',               ltp: 14.20,   sector: 'Travel',            lotSize: L1 },
  { symbol: 'YATRA',       name: 'Yatra Online',                     ltp: 130.40,  sector: 'Travel',            lotSize: L1 },
  { symbol: 'IRCTC',       name: 'Indian Railway Catering & Tourism', ltp: 800.50, sector: 'Travel',           lotSize: L1 },

  // ---------------- Engineering & Industrial ----------------
  { symbol: 'ABB',         name: 'ABB India',                        ltp: 8000.20, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'SIEMENS',     name: 'Siemens India',                    ltp: 7000.40, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'BHEL',        name: 'Bharat Heavy Electricals',         ltp: 240.50,  sector: 'Engineering',       lotSize: L1 },
  { symbol: 'ABBOTINDIA2', name: 'ABB Power Products',               ltp: 3500.20, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'CUMMINSIND',  name: 'Cummins India',                    ltp: 3500.40, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'THERMAX',     name: 'Thermax Ltd',                      ltp: 4400.50, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'INFRATEL',    name: 'Bharti Infratel',                  ltp: 200.20,  sector: 'Engineering',       lotSize: L1 },
  { symbol: 'ELECON',      name: 'Elecon Engineering',               ltp: 1100.40, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'ACTIONCON',   name: 'Action Construction Equip',        ltp: 1100.50, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'KSB',         name: 'KSB Limited',                      ltp: 3500.20, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'KIRLOSKAR',   name: 'Kirloskar Brothers',               ltp: 1500.40, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'KIRLOSENG',   name: 'Kirloskar Engines India',          ltp: 4400.50, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'KIRLOIL',     name: 'Kirloskar Oil Engines',            ltp: 540.20,  sector: 'Engineering',       lotSize: L1 },
  { symbol: 'HINDMOTOR',   name: 'Hindustan Motors',                 ltp: 14.20,   sector: 'Engineering',       lotSize: L1 },
  { symbol: 'SWARAJENG',   name: 'Swaraj Engines',                   ltp: 2400.40, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'VSTIND',      name: 'VST Tillers Tractors',             ltp: 3500.50, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'ESABINDIA',   name: 'ESAB India',                       ltp: 2400.20, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'HBLPOWER',    name: 'HBL Power Systems',                ltp: 540.40,  sector: 'Engineering',       lotSize: L1 },

  // ---------------- Real Estate ----------------
  { symbol: 'DLF',         name: 'DLF Ltd',                          ltp: 800.50,  sector: 'Realty',           lotSize: L1 },
  { symbol: 'GODREJPROP',  name: 'Godrej Properties',                ltp: 2400.20, sector: 'Realty',           lotSize: L1 },
  { symbol: 'OBEROIRLTY',  name: 'Oberoi Realty',                    ltp: 1500.40, sector: 'Realty',           lotSize: L1 },
  { symbol: 'PRESTIGE',    name: 'Prestige Estates Projects',        ltp: 1300.20, sector: 'Realty',           lotSize: L1 },
  { symbol: 'BRIGADE',     name: 'Brigade Enterprises',              ltp: 130.50,  sector: 'Realty',           lotSize: L1 },
  { symbol: 'SOBHA',       name: 'Sobha Ltd',                        ltp: 1500.40, sector: 'Realty',           lotSize: L1 },
  { symbol: 'PHOENIXTOWN', name: 'The Phoenix Mills',                ltp: 1700.20, sector: 'Realty',           lotSize: L1 },
  { symbol: 'LODHA',       name: 'Macrotech Developers (Lodha)',     ltp: 1100.50, sector: 'Realty',           lotSize: L1 },
  { symbol: 'MAHLIFE',     name: 'Mahindra Lifespace',               ltp: 410.40,  sector: 'Realty',           lotSize: L1 },
  { symbol: 'AMBUJAENTE',  name: 'Ambuja Enterprises',               ltp: 540.20,  sector: 'Realty',           lotSize: L1 },

  // ---------------- Electric Vehicles & New Age ----------------
  { symbol: 'MARUTI-SUZUKI', name: 'Maruti Suzuki (ev variant)',     ltp: 12450.20, sector: 'EV',              lotSize: L1 },
  { symbol: 'TATA MOTORS EV', name: 'Tata Motors EV',                ltp: 320.40,  sector: 'EV',                lotSize: L1 },
  { symbol: 'M&M-EV',      name: 'Mahindra Electric',                ltp: 940.20,  sector: 'EV',                lotSize: L1 },
  { symbol: 'GREAVESCOT',  name: 'Greaves Cotton',                   ltp: 180.50,  sector: 'EV',                lotSize: L1 },
  { symbol: 'EXICOM',      name: 'Exicom Tele-Systems',              ltp: 280.40,  sector: 'EV',                lotSize: L1 },
  { symbol: 'OLECTRA',     name: 'Olectra Greentech',                ltp: 1700.20, sector: 'EV',                lotSize: L1 },
  { symbol: 'TATA POWER EV', name: 'Tata Power (EV charging)',      ltp: 320.50,  sector: 'EV',                lotSize: L1 },

  // ---------------- Jewellery & Luxury ----------------
  { symbol: 'TITAN-JEWEL', name: 'Titan (Jewellery)',                ltp: 3400.50, sector: 'Jewellery',         lotSize: L1 },
  { symbol: 'KALYANKJIL',  name: 'Kalyan Jewellers India',           ltp: 410.20,  sector: 'Jewellery',         lotSize: L1 },
  { symbol: 'SUNTECK',     name: 'Sunteck Realty',                   ltp: 410.50,  sector: 'Jewellery',         lotSize: L1 },
  { symbol: 'TBZ',         name: 'Tribhovandas Bhimji Zaveri',       ltp: 50.20,   sector: 'Jewellery',         lotSize: L1 },
  { symbol: 'PCJEWELLER',  name: 'PC Jeweller',                      ltp: 14.50,   sector: 'Jewellery',         lotSize: L1 },
  { symbol: 'TARA JEWELS', name: 'Tara Jewels Ltd',                  ltp: 5.40,    sector: 'Jewellery',         lotSize: L1 },

  // ---------------- Logistics ----------------
  { symbol: 'BLUEDART',    name: 'Blue Dart Express',                ltp: 8000.20, sector: 'Logistics',         lotSize: L1 },
  { symbol: 'TCI',         name: 'Transport Corporation of India',   ltp: 800.40,  sector: 'Logistics',         lotSize: L1 },
  { symbol: 'ALLCARGO',    name: 'Allcargo Logistics',               ltp: 80.20,   sector: 'Logistics',         lotSize: L1 },
  { symbol: 'MAHINDRA LOGI', name: 'Mahindra Logistics',             ltp: 540.40,  sector: 'Logistics',         lotSize: L1 },
  { symbol: 'CONTAINER',   name: 'Container Corporation of India',   ltp: 1100.50, sector: 'Logistics',         lotSize: L1 },
  { symbol: 'DELHIVERY',   name: 'Delhivery Ltd',                    ltp: 410.20,  sector: 'Logistics',         lotSize: L1 },

  // ---------------- Healthcare Services ----------------
  { symbol: 'APOLLOHOSP',  name: 'Apollo Hospitals Enterprise',      ltp: 6500.20, sector: 'Healthcare',        lotSize: L1 },
  { symbol: 'FORTIS',      name: 'Fortis Healthcare',                ltp: 410.40,  sector: 'Healthcare',        lotSize: L1 },
  { symbol: 'MAXHEALTH',   name: 'Max Healthcare Institute',         ltp: 800.50,  sector: 'Healthcare',        lotSize: L1 },
  { symbol: 'NH',          name: 'Narayana Hrudayalaya',             ltp: 1300.20, sector: 'Healthcare',        lotSize: L1 },
  { symbol: 'GLOBALHOSP',  name: 'Global Health (Medanta)',          ltp: 1100.40, sector: 'Healthcare',        lotSize: L1 },
  { symbol: 'KMC',         name: 'KMC Speciality Hospitals',         ltp: 100.20,  sector: 'Healthcare',        lotSize: L1 },
  { symbol: 'RAINBOW',     name: 'Rainbow Children Medicare',        ltp: 1100.40, sector: 'Healthcare',        lotSize: L1 },
  { symbol: 'AGRI-TECH',   name: 'Agri-Tech (India)',                ltp: 70.20,   sector: 'Healthcare',        lotSize: L1 },

  // ---------------- Dairy & Protein ----------------
  { symbol: 'AMUL',        name: 'Amul (GCMMF)',                     ltp: 50.20,   sector: 'Dairy',             lotSize: L1 },
  { symbol: 'HERITGFOOD',  name: 'Heritage Foods',                   ltp: 410.40,  sector: 'Dairy',             lotSize: L1 },
  { symbol: 'PRABHAT',     name: 'Prabhat Dairy',                    ltp: 70.20,   sector: 'Dairy',             lotSize: L1 },
  { symbol: 'KARNATAKA BANK', name: 'Karnataka Bank Ltd',            ltp: 200.10,  sector: 'Banking',           lotSize: L1 },
  { symbol: 'CITYUNION',   name: 'City Union Bank Ltd',              ltp: 150.50,  sector: 'Banking',           lotSize: L1 },

  // ---------------- Misc Conglomerates ----------------
  { symbol: 'ADANIENT',    name: 'Adani Enterprises',                ltp: 2890.45, sector: 'Conglomerate',      lotSize: 250 },
  { symbol: 'ADANIPORTS',  name: 'Adani Ports & SEZ',                ltp: 1300.20, sector: 'Conglomerate',      lotSize: L1 },
  { symbol: 'BAJAJHLDNG2', name: 'Bajaj Holdings & Investment',      ltp: 8000.10, sector: 'Conglomerate',      lotSize: L1 },
  { symbol: 'TTKCHH',      name: 'TTK Healthcare',                   ltp: 1400.20, sector: 'Conglomerate',      lotSize: L1 },
  { symbol: 'TATA INVEST', name: 'Tata Investment Corporation',      ltp: 4400.40, sector: 'Conglomerate',      lotSize: L1 },
  { symbol: 'BAJAJELECT',  name: 'Bajaj Electricals',                ltp: 1100.20, sector: 'Conglomerate',      lotSize: L1 },
  { symbol: 'ZUARI',       name: 'Zuari Agro Chemicals',             ltp: 200.40,  sector: 'Agri',              lotSize: L1 },
  { symbol: 'MANGALAM',    name: 'Mangalam Cement',                  ltp: 380.50,  sector: 'Cement',            lotSize: L1 },
  { symbol: 'HEG',         name: 'HEG Ltd',                          ltp: 410.20,  sector: 'Metals',            lotSize: L1 },
  { symbol: 'CARBORUNDUM', name: 'Carborundum Universal',            ltp: 1100.40, sector: 'Metals',            lotSize: L1 },
  { symbol: 'MIDHANI',     name: 'Mishra Dhatu Nigam',               ltp: 280.20,  sector: 'Metals',            lotSize: L1 },
  { symbol: 'BAJAJ CONSUM', name: 'Bajaj Consumer Care',             ltp: 220.50,  sector: 'Consumer',          lotSize: L1 },

  // ---------------- Brewery & Spirits ----------------
  { symbol: 'GMBREW',      name: 'GM Breweries',                     ltp: 540.20,  sector: 'Brewery',           lotSize: L1 },
  { symbol: 'EMBASSY',     name: 'Embassy Developments',             ltp: 80.40,   sector: 'Realty',            lotSize: L1 },
  { symbol: 'SKFINDIA',    name: 'SKF India',                        ltp: 4400.20, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'TIMKEN',      name: 'Timken India',                     ltp: 3000.40, sector: 'Engineering',       lotSize: L1 },
  { symbol: 'SCHNEIDER',   name: 'Schneider Electric India',         ltp: 350.50,  sector: 'Engineering',       lotSize: L1 },
  { symbol: 'BHEL-EV',     name: 'BHEL EV Initiatives',              ltp: 240.20,  sector: 'Engineering',       lotSize: L1 },

  // ---------------- Additional mid & small caps ----------------
  { symbol: 'CENTRUM',     name: 'Centrum Capital',                  ltp: 30.20,   sector: 'Finance',           lotSize: L1 },
  { symbol: 'EDL',         name: 'Edelweiss Financial Services',     ltp: 70.40,   sector: 'Finance',           lotSize: L1 },
  { symbol: 'GE Power',    name: 'GE Power India',                   ltp: 200.50,  sector: 'Engineering',       lotSize: L1 },
  { symbol: 'GESHIP',      name: 'Great Eastern Shipping',           ltp: 800.20,  sector: 'Logistics',         lotSize: L1 },
  { symbol: 'SCI',         name: 'Shipping Corporation of India',    ltp: 130.40,  sector: 'Logistics',         lotSize: L1 },
  { symbol: 'AVADH',       name: 'Avadh Sugar & Energy',             ltp: 410.20,  sector: 'Sugar',             lotSize: L1 },
  { symbol: 'BANNARI',     name: 'Bannari Amman Spinning',           ltp: 100.50,  sector: 'Textiles',          lotSize: L1 },
  { symbol: 'KITEXGAR',    name: 'Kitex Garments',                   ltp: 200.20,  sector: 'Textiles',          lotSize: L1 },
  { symbol: 'DCM Shriram', name: 'DCM Shriram Ltd',                  ltp: 1000.40, sector: 'Conglomerate',      lotSize: L1 },
  { symbol: 'EICHERMOT2',  name: 'Eicher Motors (Commercial)',       ltp: 4900.50, sector: 'Automobile',        lotSize: L1 },
  { symbol: 'KESORAM',     name: 'Kesoram Industries',               ltp: 130.20,  sector: 'Cement',            lotSize: L1 },
  { symbol: 'EIH',         name: 'EIH Ltd',                          ltp: 320.40,  sector: 'Hospitality',       lotSize: L1 },
  { symbol: 'CHOLAFIN2',   name: 'Cholamandalam Finance',            ltp: 1200.50, sector: 'Finance',           lotSize: L1 },
  { symbol: 'LICHF',       name: 'LIC Housing Finance',              ltp: 540.20,  sector: 'Finance',           lotSize: L1 },
  { symbol: 'PNBHOUSING',  name: 'PNB Housing Finance',              ltp: 410.40,  sector: 'Finance',           lotSize: L1 },
  { symbol: 'AUSTIN',      name: 'Austin Engineering',               ltp: 30.20,   sector: 'Engineering',       lotSize: L1 },
  { symbol: 'GNA',         name: 'GNA Axles',                        ltp: 100.50,  sector: 'Auto Parts',        lotSize: L1 },
  { symbol: 'SURYODAY',    name: 'Suryoday Small Finance Bank',      ltp: 130.40,  sector: 'Banking',           lotSize: L1 },
  { symbol: 'UJJIVAN',     name: 'Ujjivan Small Finance Bank',       ltp: 50.20,   sector: 'Banking',           lotSize: L1 },
  { symbol: 'EQUITAS',     name: 'Equitas Small Finance Bank',       ltp: 70.40,   sector: 'Banking',           lotSize: L1 },
  { symbol: 'CREDITACC',   name: 'CreditAccess Grameen',             ltp: 970.50,  sector: 'Finance',           lotSize: L1 },
  { symbol: 'SPANDANA',    name: 'Spandana Sphoorty Financial',      ltp: 540.20,  sector: 'Finance',           lotSize: L1 },
  { symbol: 'MASFIN',      name: 'MAS Financial Services',           ltp: 240.40,  sector: 'Finance',           lotSize: L1 },
  { symbol: 'ARMANFIN',    name: 'Arman Financial Services',         ltp: 540.20,  sector: 'Finance',           lotSize: L1 },
  { symbol: 'FIVESTAR',    name: 'Five-Star Business Finance',       ltp: 540.20,  sector: 'Finance',           lotSize: L1 },

  // ---------------- Tech & SaaS ----------------
  { symbol: 'TATA ELXSI',  name: 'Tata Elxsi',                       ltp: 6800.50, sector: 'IT',                lotSize: L1 },
  { symbol: 'KFINTECH',    name: 'KFin Technologies',                ltp: 800.40,  sector: 'IT',                lotSize: L1 },
  { symbol: 'CAMSSERVICES', name: 'Computer Age Management Services', ltp: 2400.20, sector: 'IT',              lotSize: L1 },
  { symbol: 'MAPMYINDIA',  name: 'C.E. Info Systems (MapMyIndia)',   ltp: 2400.50, sector: 'IT',               lotSize: L1 },
  { symbol: 'RATESENS',    name: 'Rategain Travel Technologies',     ltp: 540.20,  sector: 'IT',                lotSize: L1 },
  { symbol: 'TBO TEK',     name: 'TBO Tek Ltd',                      ltp: 1500.40, sector: 'IT',                lotSize: L1 },
  { symbol: 'KAYNES',      name: 'Kaynes Technology India',          ltp: 3500.20, sector: 'IT',                lotSize: L1 },
  { symbol: 'DIXONTECH',   name: 'Dixon Technologies India',         ltp: 13000.20, sector: 'IT',               lotSize: L1 },
  { symbol: 'AVALON',      name: 'Avalon Technologies',              ltp: 540.40,  sector: 'IT',                lotSize: L1 },
  { symbol: 'Syrma SGS',   name: 'Syrma SGS Technology',             ltp: 540.20,  sector: 'IT',                lotSize: L1 },
  { symbol: 'HAPPY FORGE', name: 'Happy Forgings',                   ltp: 800.50,  sector: 'Engineering',       lotSize: L1 },
  { symbol: 'EXRO',        name: 'Exro Technologies',                ltp: 5.40,    sector: 'Engineering',       lotSize: L1 },

  // ---------------- ETFs & Index Funds ----------------
  { symbol: 'NIFTYBEES',   name: 'Nippon India ETF Nifty 50',        ltp: 240.20,  sector: 'ETF',               lotSize: L1 },
  { symbol: 'BANKBEES',    name: 'Nippon India ETF Bank Nifty',      ltp: 440.40,  sector: 'ETF',               lotSize: L1 },
  { symbol: 'GOLDBEES',    name: 'Nippon India ETF Gold',            ltp: 60.50,   sector: 'ETF',               lotSize: L1 },
  { symbol: 'ITBEES',      name: 'Nippon India ETF IT',              ltp: 410.20,  sector: 'ETF',               lotSize: L1 },
  { symbol: 'PHARMABEES',  name: 'Nippon India ETF Pharma',          ltp: 180.40,  sector: 'ETF',               lotSize: L1 },
  { symbol: 'LIQUIDBEES',  name: 'Nippon India ETF Liquid',          ltp: 1000.20, sector: 'ETF',               lotSize: L1 },
  { symbol: 'HDFCSML250',  name: 'HDFC SML250',                      ltp: 130.50,  sector: 'ETF',               lotSize: L1 },
  { symbol: 'MID150BEES',  name: 'Nippon India ETF Midcap 150',      ltp: 130.20,  sector: 'ETF',               lotSize: L1 },

  // ---------------- Power Equipment & Renewable ----------------
  { symbol: 'KPIGREEN',    name: 'KPI Green Energy',                 ltp: 800.40,  sector: 'Energy',            lotSize: L1 },
  { symbol: 'SUNGOLD',     name: 'Sungold Capital',                  ltp: 14.20,   sector: 'Energy',            lotSize: L1 },
  { symbol: 'ORIENT GREEN', name: 'Orient Green Power',              ltp: 5.40,    sector: 'Energy',            lotSize: L1 },
  { symbol: 'WEBSOL',      name: 'Websol Energy System',             ltp: 5.40,    sector: 'Energy',            lotSize: L1 },
  { symbol: 'SOLARWIND',   name: 'Solarwind Power Systems',          ltp: 5.40,    sector: 'Energy',            lotSize: L1 },
  { symbol: 'INDOSOLAR',   name: 'Indosolar Ltd',                    ltp: 14.20,   sector: 'Energy',            lotSize: L1 },
  { symbol: 'BRIGHTSOLAR', name: 'Bright Solar Ltd',                 ltp: 5.40,    sector: 'Energy',            lotSize: L1 },
  { symbol: 'GIPCL',       name: 'Gujarat Industries Power',         ltp: 280.20,  sector: 'Energy',            lotSize: L1 },
  { symbol: 'CESC',        name: 'CESC Ltd',                         ltp: 130.40,  sector: 'Energy',            lotSize: L1 },
  { symbol: 'TATA POWER CO', name: 'Tata Power Co. (Renewables)',    ltp: 320.50,  sector: 'Energy',            lotSize: L1 },
];

// Export as a deduplicated array (some symbols may have appeared more than
// once in the source list — keep only the first occurrence so seeding is
// idempotent).
export const DEDUPED_STOCKS: StockSeed[] = (() => {
  const seen = new Set<string>();
  const out: StockSeed[] = [];
  for (const s of STOCKS_UNIVERSE) {
    const key = s.symbol.toUpperCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(s);
  }
  return out;
})();
